### ISSUE TITLE
Range filter and own condition

### ISSUE THREAD

**Issue by cv65kr** [apisearch-io/search-ui#17]
Hi!
Two fast questions:
1. How to create range filter?
2. How to add own condition to search, which can no visible in filters, e.g.  I have static page with category `?category_id =300`, and I want saw only items only from this category without button check filter.

**Comment by mmoreram** [comment]
1 - http://docs.apisearch.io/api-client/query.html#filter-by-range
2 - In fact, you should. There was a PR covered by myself that was actually covering this part inside the UI. By adding an anonymous function, you had the option to make an static filter, applied always in a transparent way. After an entire refactoring of the library, that was gone.

I will add this functionality again this afternoon :) Let's keep this Issue opened for that.

**Comment by cv65kr** [comment]
1. I saw that, but in my mind I am thinking about some widget to SearchUI
2. So I will wait for that :)

**Comment by mmoreram** [comment]
Oh, you mean the widget.
This is not implemented yet :(

**Comment by mmoreram** [comment]
We could close this issue, and open a new one for the Range filter.
Second one is solved in #19

**Comment by mmoreram** [comment]
Closed because ranges are already implemented :) - https://github.com/apisearch-io/search-ui/pull/29
